# @package eval.mia_passage_wikipedia.metrics.mia_min_k_plus_plus
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: mia_min_k_plus_plus
batch_size: 8
k: 40  # Default k value, adjust as needed

datasets:
  forget:
    handler: CompletionDataset
    args:
      hf_args:
        path: json
        data_files: "/NS/llm-pretraining/work/afkhan/HubbleSuite/open-unlearning/Hubble_Data/passages_wikipedia_train.jsonl"
        trust_remote_code: true
        split: "train"
      max_length: 10000
  holdout:
    handler: CompletionDataset
    args:
      hf_args:
        path: json
        data_files: "/NS/llm-pretraining/work/afkhan/HubbleSuite/open-unlearning/Hubble_Data/passages_wikipedia_test.jsonl"
        trust_remote_code: true
        split: "train"
      max_length: 10000