model_args:
  pretrained_model_name_or_path: "allegrolab/hubble-8b-500b_toks-perturbed-hf"
  attn_implementation: 'flash_attention_2'
  torch_dtype: bfloat16
tokenizer_args:
  pretrained_model_name_or_path: "allegrolab/hubble-8b-500b_toks-perturbed-hf"
template_args:
  apply_chat_template: false
  user_start_tag: ""
  user_end_tag: ""
  asst_start_tag: ""
  asst_end_tag: ""