local_model_path: ???

model_args:
  pretrained_model_name_or_path: ${model.local_model_path}
  attn_implementation: sdpa
  torch_dtype: bfloat16

tokenizer_args:
  pretrained_model_name_or_path: ${model.local_model_path}

template_args:
  apply_chat_template: false
  user_start_tag: ""
  user_end_tag: ""
  asst_start_tag: ""
  asst_end_tag: ""
