# @package eval.custom_mia.metrics.mia_min_k_plus_plus
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: mia_min_k_plus_plus
batch_size: 8
k: 40  # Default k value, adjust as needed

datasets:
  forget:
    handler: CompletionDataset
    args:
      hf_args:
        path: json
        data_files: "${mia_data_root}/${mia_corpus}/members.jsonl"
        trust_remote_code: true
        split: "train"
      max_length: 512
  holdout:
    handler: CompletionDataset
    args:
      hf_args:
        path: json
        data_files: "${mia_data_root}/${mia_corpus}/unseen.jsonl"
        trust_remote_code: true
        split: "train"
      max_length: 512
