# @package eval.custom_mia.metrics.mia_loss
defaults:
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: mia_loss
batch_size: 8

datasets:
  forget:
    handler: CompletionDataset
    args:
      hf_args:
        path: json
        data_files: "/NS/llm-pretraining/work/afkhan/HubbleSuite/seen.jsonl"
        trust_remote_code: true
        split: "train"
      max_length: 512
  holdout:
    handler: CompletionDataset
    args:
      hf_args:
        path: json
        data_files: "/NS/llm-pretraining/work/afkhan/HubbleSuite/holdout.jsonl"
        trust_remote_code: true
        split: "train"
      max_length: 512